<?php

// Data functions (insert, update, delete, form) for table feescollection

// This script and data application were generated by AppGini 5.70
// Download AppGini for free from https://bigprof.com/appgini/download/

function feescollection_insert(){
	global $Translation;

	// mm: can member insert record?
	$arrPerm=getTablePermissions('feescollection');
	if(!$arrPerm[1]){
		return false;
	}

	$data['Student'] = makeSafe($_REQUEST['Student']);
		if($data['Student'] == empty_lookup_value){ $data['Student'] = ''; }
	$data['Class'] = makeSafe($_REQUEST['Student']);
		if($data['Class'] == empty_lookup_value){ $data['Class'] = ''; }
	$data['Session'] = makeSafe($_REQUEST['Session']);
		if($data['Session'] == empty_lookup_value){ $data['Session'] = ''; }
	$data['PaidAmount'] = makeSafe($_REQUEST['PaidAmount']);
		if($data['PaidAmount'] == empty_lookup_value){ $data['PaidAmount'] = ''; }
	$data['Balance'] = makeSafe($_REQUEST['Student']);
		if($data['Balance'] == empty_lookup_value){ $data['Balance'] = ''; }
	$data['Branch'] = makeSafe($_REQUEST['Branch']);
		if($data['Branch'] == empty_lookup_value){ $data['Branch'] = ''; }
	$data['Date'] = parseCode('<%%creationDate%%>', true, true);
	$data['Remarks'] = br2nl(makeSafe($_REQUEST['Remarks']));
	if($data['Student']== ''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">" . $Translation['error:'] . " 'Student': " . $Translation['field not null'] . '<br><br>';
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	if($data['Session']== ''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">" . $Translation['error:'] . " 'Session': " . $Translation['field not null'] . '<br><br>';
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	if($data['PaidAmount']== ''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">" . $Translation['error:'] . " 'PaidAmount (Ksh)': " . $Translation['field not null'] . '<br><br>';
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	if($data['Branch']== ''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">" . $Translation['error:'] . " 'Branch': " . $Translation['field not null'] . '<br><br>';
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}

	// hook: feescollection_before_insert
	if(function_exists('feescollection_before_insert')){
		$args=array();
		if(!feescollection_before_insert($data, getMemberInfo(), $args)){ return false; }
	}

	$o = array('silentErrors' => true);
	sql('insert into `feescollection` set       `Student`=' . (($data['Student'] !== '' && $data['Student'] !== NULL) ? "'{$data['Student']}'" : 'NULL') . ', `Class`=' . (($data['Class'] !== '' && $data['Class'] !== NULL) ? "'{$data['Class']}'" : 'NULL') . ', `Session`=' . (($data['Session'] !== '' && $data['Session'] !== NULL) ? "'{$data['Session']}'" : 'NULL') . ', `PaidAmount`=' . (($data['PaidAmount'] !== '' && $data['PaidAmount'] !== NULL) ? "'{$data['PaidAmount']}'" : 'NULL') . ', `Balance`=' . (($data['Balance'] !== '' && $data['Balance'] !== NULL) ? "'{$data['Balance']}'" : 'NULL') . ', `Branch`=' . (($data['Branch'] !== '' && $data['Branch'] !== NULL) ? "'{$data['Branch']}'" : 'NULL') . ', `Date`=' . "'{$data['Date']}'" . ', `Remarks`=' . (($data['Remarks'] !== '' && $data['Remarks'] !== NULL) ? "'{$data['Remarks']}'" : 'NULL'), $o);
	if($o['error']!=''){
		echo $o['error'];
		echo "<a href=\"feescollection_view.php?addNew_x=1\">{$Translation['< back']}</a>";
		exit;
	}

	$recID = db_insert_id(db_link());

	// hook: feescollection_after_insert
	if(function_exists('feescollection_after_insert')){
		$res = sql("select * from `feescollection` where `id`='" . makeSafe($recID, false) . "' limit 1", $eo);
		if($row = db_fetch_assoc($res)){
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = makeSafe($recID, false);
		$args=array();
		if(!feescollection_after_insert($data, getMemberInfo(), $args)){ return $recID; }
	}

	// mm: save ownership data
	set_record_owner('feescollection', $recID, getLoggedMemberID());

	return $recID;
}

function feescollection_delete($selected_id, $AllowDeleteOfParents=false, $skipChecks=false){
	// insure referential integrity ...
	global $Translation;
	$selected_id=makeSafe($selected_id);

	// mm: can member delete record?
	$arrPerm=getTablePermissions('feescollection');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='feescollection' and pkValue='$selected_id'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='feescollection' and pkValue='$selected_id'");
	if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3){ // allow delete?
		// delete allowed, so continue ...
	}else{
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: feescollection_before_delete
	if(function_exists('feescollection_before_delete')){
		$args=array();
		if(!feescollection_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'];
	}

	sql("delete from `feescollection` where `id`='$selected_id'", $eo);

	// hook: feescollection_after_delete
	if(function_exists('feescollection_after_delete')){
		$args=array();
		feescollection_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("delete from membership_userrecords where tableName='feescollection' and pkValue='$selected_id'", $eo);
}

function feescollection_update($selected_id){
	global $Translation;

	// mm: can member edit record?
	$arrPerm=getTablePermissions('feescollection');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='feescollection' and pkValue='".makeSafe($selected_id)."'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='feescollection' and pkValue='".makeSafe($selected_id)."'");
	if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3){ // allow update?
		// update allowed, so continue ...
	}else{
		return false;
	}

	$data['Student'] = makeSafe($_REQUEST['Student']);
		if($data['Student'] == empty_lookup_value){ $data['Student'] = ''; }
	if($data['Student']==''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Student': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	$data['Class'] = makeSafe($_REQUEST['Student']);
		if($data['Class'] == empty_lookup_value){ $data['Class'] = ''; }
	$data['Session'] = makeSafe($_REQUEST['Session']);
		if($data['Session'] == empty_lookup_value){ $data['Session'] = ''; }
	if($data['Session']==''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Session': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	$data['PaidAmount'] = makeSafe($_REQUEST['PaidAmount']);
		if($data['PaidAmount'] == empty_lookup_value){ $data['PaidAmount'] = ''; }
	if($data['PaidAmount']==''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'PaidAmount (Ksh)': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	$data['Balance'] = makeSafe($_REQUEST['Student']);
		if($data['Balance'] == empty_lookup_value){ $data['Balance'] = ''; }
	$data['Branch'] = makeSafe($_REQUEST['Branch']);
		if($data['Branch'] == empty_lookup_value){ $data['Branch'] = ''; }
	if($data['Branch']==''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Branch': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	$data['Date'] = parseMySQLDate('', '<%%creationDate%%>');
	$data['Remarks'] = br2nl(makeSafe($_REQUEST['Remarks']));
	$data['selectedID']=makeSafe($selected_id);

	// hook: feescollection_before_update
	if(function_exists('feescollection_before_update')){
		$args=array();
		if(!feescollection_before_update($data, getMemberInfo(), $args)){ return false; }
	}

	$o=array('silentErrors' => true);
	sql('update `feescollection` set       `Student`=' . (($data['Student'] !== '' && $data['Student'] !== NULL) ? "'{$data['Student']}'" : 'NULL') . ', `Class`=' . (($data['Class'] !== '' && $data['Class'] !== NULL) ? "'{$data['Class']}'" : 'NULL') . ', `Session`=' . (($data['Session'] !== '' && $data['Session'] !== NULL) ? "'{$data['Session']}'" : 'NULL') . ', `PaidAmount`=' . (($data['PaidAmount'] !== '' && $data['PaidAmount'] !== NULL) ? "'{$data['PaidAmount']}'" : 'NULL') . ', `Balance`=' . (($data['Balance'] !== '' && $data['Balance'] !== NULL) ? "'{$data['Balance']}'" : 'NULL') . ', `Branch`=' . (($data['Branch'] !== '' && $data['Branch'] !== NULL) ? "'{$data['Branch']}'" : 'NULL') . ', `Date`=`Date`' . ', `Remarks`=' . (($data['Remarks'] !== '' && $data['Remarks'] !== NULL) ? "'{$data['Remarks']}'" : 'NULL') . " where `id`='".makeSafe($selected_id)."'", $o);
	if($o['error']!=''){
		echo $o['error'];
		echo '<a href="feescollection_view.php?SelectedID='.urlencode($selected_id)."\">{$Translation['< back']}</a>";
		exit;
	}


	// hook: feescollection_after_update
	if(function_exists('feescollection_after_update')){
		$res = sql("SELECT * FROM `feescollection` WHERE `id`='{$data['selectedID']}' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)){
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = $data['id'];
		$args = array();
		if(!feescollection_after_update($data, getMemberInfo(), $args)){ return; }
	}

	// mm: update ownership data
	sql("update membership_userrecords set dateUpdated='".time()."' where tableName='feescollection' and pkValue='".makeSafe($selected_id)."'", $eo);

}

function feescollection_form($selected_id = '', $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1, $ShowCancel = 0, $TemplateDV = '', $TemplateDVP = ''){
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;

	// mm: get table permissions
	$arrPerm=getTablePermissions('feescollection');
	if(!$arrPerm[1] && $selected_id==''){ return ''; }
	$AllowInsert = ($arrPerm[1] ? true : false);
	// print preview?
	$dvprint = false;
	if($selected_id && $_REQUEST['dvprint_x'] != ''){
		$dvprint = true;
	}

	$filterer_Student = thisOr(undo_magic_quotes($_REQUEST['filterer_Student']), '');
	$filterer_Session = thisOr(undo_magic_quotes($_REQUEST['filterer_Session']), '');
	$filterer_Branch = thisOr(undo_magic_quotes($_REQUEST['filterer_Branch']), '');

	// populate filterers, starting from children to grand-parents

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');
	// combobox: Student
	$combo_Student = new DataCombo;
	// combobox: Session
	$combo_Session = new DataCombo;
	// combobox: Branch
	$combo_Branch = new DataCombo;
	// combobox: Date
	$combo_Date = new DateCombo;
	$combo_Date->DateFormat = "mdy";
	$combo_Date->MinYear = 1900;
	$combo_Date->MaxYear = 2100;
	$combo_Date->DefaultDate = parseMySQLDate('<%%creationDate%%>', '<%%creationDate%%>');
	$combo_Date->MonthNames = $Translation['month names'];
	$combo_Date->NamePrefix = 'Date';

	if($selected_id){
		// mm: check member permissions
		if(!$arrPerm[2]){
			return "";
		}
		// mm: who is the owner?
		$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='feescollection' and pkValue='".makeSafe($selected_id)."'");
		$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='feescollection' and pkValue='".makeSafe($selected_id)."'");
		if($arrPerm[2]==1 && getLoggedMemberID()!=$ownerMemberID){
			return "";
		}
		if($arrPerm[2]==2 && getLoggedGroupID()!=$ownerGroupID){
			return "";
		}

		// can edit?
		if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3){
			$AllowUpdate=1;
		}else{
			$AllowUpdate=0;
		}

		$res = sql("select * from `feescollection` where `id`='".makeSafe($selected_id)."'", $eo);
		if(!($row = db_fetch_array($res))){
			return error_message($Translation['No records found'], 'feescollection_view.php', false);
		}
		$urow = $row; /* unsanitized data */
		$hc = new CI_Input();
		$row = $hc->xss_clean($row); /* sanitize data */
		$combo_Student->SelectedData = $row['Student'];
		$combo_Session->SelectedData = $row['Session'];
		$combo_Branch->SelectedData = $row['Branch'];
		$combo_Date->DefaultDate = $row['Date'];
	}else{
		$combo_Student->SelectedData = $filterer_Student;
		$combo_Session->SelectedData = $filterer_Session;
		$combo_Branch->SelectedData = $filterer_Branch;
	}
	$combo_Student->HTML = '<span id="Student-container' . $rnd1 . '"></span><input type="hidden" name="Student" id="Student' . $rnd1 . '" value="' . html_attr($combo_Student->SelectedData) . '">';
	$combo_Student->MatchText = '<span id="Student-container-readonly' . $rnd1 . '"></span><input type="hidden" name="Student" id="Student' . $rnd1 . '" value="' . html_attr($combo_Student->SelectedData) . '">';
	$combo_Session->HTML = '<span id="Session-container' . $rnd1 . '"></span><input type="hidden" name="Session" id="Session' . $rnd1 . '" value="' . html_attr($combo_Session->SelectedData) . '">';
	$combo_Session->MatchText = '<span id="Session-container-readonly' . $rnd1 . '"></span><input type="hidden" name="Session" id="Session' . $rnd1 . '" value="' . html_attr($combo_Session->SelectedData) . '">';
	$combo_Branch->HTML = '<span id="Branch-container' . $rnd1 . '"></span><input type="hidden" name="Branch" id="Branch' . $rnd1 . '" value="' . html_attr($combo_Branch->SelectedData) . '">';
	$combo_Branch->MatchText = '<span id="Branch-container-readonly' . $rnd1 . '"></span><input type="hidden" name="Branch" id="Branch' . $rnd1 . '" value="' . html_attr($combo_Branch->SelectedData) . '">';

	ob_start();
	?>

	<script>
		// initial lookup values
		AppGini.current_Student__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['Student'] : $filterer_Student); ?>"};
		AppGini.current_Session__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['Session'] : $filterer_Session); ?>"};
		AppGini.current_Branch__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['Branch'] : $filterer_Branch); ?>"};

		jQuery(function() {
			setTimeout(function(){
				if(typeof(Student_reload__RAND__) == 'function') Student_reload__RAND__();
				if(typeof(Session_reload__RAND__) == 'function') Session_reload__RAND__();
				if(typeof(Branch_reload__RAND__) == 'function') Branch_reload__RAND__();
			}, 10); /* we need to slightly delay client-side execution of the above code to allow AppGini.ajaxCache to work */
		});
		function Student_reload__RAND__(){
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint){ ?>

			$j("#Student-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c){
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_Student__RAND__.value, t: 'feescollection', f: 'Student' },
						success: function(resp){
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="Student"]').val(resp.results[0].id);
							$j('[id=Student-container-readonly__RAND__]').html('<span id="Student-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=students_view_parent]').hide(); }else{ $j('.btn[id=students_view_parent]').show(); }


							if(typeof(Student_update_autofills__RAND__) == 'function') Student_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term){ return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 10,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page){ return { s: term, p: page, t: 'feescollection', f: 'Student' }; },
					results: function(resp, page){ return resp; }
				},
				escapeMarkup: function(str){ return str; }
			}).on('change', function(e){
				AppGini.current_Student__RAND__.value = e.added.id;
				AppGini.current_Student__RAND__.text = e.added.text;
				$j('[name="Student"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=students_view_parent]').hide(); }else{ $j('.btn[id=students_view_parent]').show(); }


				if(typeof(Student_update_autofills__RAND__) == 'function') Student_update_autofills__RAND__();
			});

			if(!$j("#Student-container__RAND__").length){
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_Student__RAND__.value, t: 'feescollection', f: 'Student' },
					success: function(resp){
						$j('[name="Student"]').val(resp.results[0].id);
						$j('[id=Student-container-readonly__RAND__]').html('<span id="Student-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=students_view_parent]').hide(); }else{ $j('.btn[id=students_view_parent]').show(); }

						if(typeof(Student_update_autofills__RAND__) == 'function') Student_update_autofills__RAND__();
					}
				});
			}

		<?php }else{ ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_Student__RAND__.value, t: 'feescollection', f: 'Student' },
				success: function(resp){
					$j('[id=Student-container__RAND__], [id=Student-container-readonly__RAND__]').html('<span id="Student-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=students_view_parent]').hide(); }else{ $j('.btn[id=students_view_parent]').show(); }

					if(typeof(Student_update_autofills__RAND__) == 'function') Student_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function Session_reload__RAND__(){
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint){ ?>

			$j("#Session-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c){
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_Session__RAND__.value, t: 'feescollection', f: 'Session' },
						success: function(resp){
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="Session"]').val(resp.results[0].id);
							$j('[id=Session-container-readonly__RAND__]').html('<span id="Session-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=sessions_view_parent]').hide(); }else{ $j('.btn[id=sessions_view_parent]').show(); }

						if(typeof(Balance_reload__RAND__) == 'function') Balance_reload__RAND__(AppGini.current_Session__RAND__.value);

							if(typeof(Session_update_autofills__RAND__) == 'function') Session_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term){ return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 10,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page){ return { s: term, p: page, t: 'feescollection', f: 'Session' }; },
					results: function(resp, page){ return resp; }
				},
				escapeMarkup: function(str){ return str; }
			}).on('change', function(e){
				AppGini.current_Session__RAND__.value = e.added.id;
				AppGini.current_Session__RAND__.text = e.added.text;
				$j('[name="Session"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=sessions_view_parent]').hide(); }else{ $j('.btn[id=sessions_view_parent]').show(); }

						if(typeof(Balance_reload__RAND__) == 'function') Balance_reload__RAND__(AppGini.current_Session__RAND__.value);

				if(typeof(Session_update_autofills__RAND__) == 'function') Session_update_autofills__RAND__();
			});

			if(!$j("#Session-container__RAND__").length){
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_Session__RAND__.value, t: 'feescollection', f: 'Session' },
					success: function(resp){
						$j('[name="Session"]').val(resp.results[0].id);
						$j('[id=Session-container-readonly__RAND__]').html('<span id="Session-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=sessions_view_parent]').hide(); }else{ $j('.btn[id=sessions_view_parent]').show(); }

						if(typeof(Session_update_autofills__RAND__) == 'function') Session_update_autofills__RAND__();
					}
				});
			}

		<?php }else{ ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_Session__RAND__.value, t: 'feescollection', f: 'Session' },
				success: function(resp){
					$j('[id=Session-container__RAND__], [id=Session-container-readonly__RAND__]').html('<span id="Session-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=sessions_view_parent]').hide(); }else{ $j('.btn[id=sessions_view_parent]').show(); }

					if(typeof(Session_update_autofills__RAND__) == 'function') Session_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function Branch_reload__RAND__(){
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint){ ?>

			$j("#Branch-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c){
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_Branch__RAND__.value, t: 'feescollection', f: 'Branch' },
						success: function(resp){
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="Branch"]').val(resp.results[0].id);
							$j('[id=Branch-container-readonly__RAND__]').html('<span id="Branch-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=branch_view_parent]').hide(); }else{ $j('.btn[id=branch_view_parent]').show(); }


							if(typeof(Branch_update_autofills__RAND__) == 'function') Branch_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term){ return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 10,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page){ return { s: term, p: page, t: 'feescollection', f: 'Branch' }; },
					results: function(resp, page){ return resp; }
				},
				escapeMarkup: function(str){ return str; }
			}).on('change', function(e){
				AppGini.current_Branch__RAND__.value = e.added.id;
				AppGini.current_Branch__RAND__.text = e.added.text;
				$j('[name="Branch"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=branch_view_parent]').hide(); }else{ $j('.btn[id=branch_view_parent]').show(); }


				if(typeof(Branch_update_autofills__RAND__) == 'function') Branch_update_autofills__RAND__();
			});

			if(!$j("#Branch-container__RAND__").length){
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_Branch__RAND__.value, t: 'feescollection', f: 'Branch' },
					success: function(resp){
						$j('[name="Branch"]').val(resp.results[0].id);
						$j('[id=Branch-container-readonly__RAND__]').html('<span id="Branch-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=branch_view_parent]').hide(); }else{ $j('.btn[id=branch_view_parent]').show(); }

						if(typeof(Branch_update_autofills__RAND__) == 'function') Branch_update_autofills__RAND__();
					}
				});
			}

		<?php }else{ ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_Branch__RAND__.value, t: 'feescollection', f: 'Branch' },
				success: function(resp){
					$j('[id=Branch-container__RAND__], [id=Branch-container-readonly__RAND__]').html('<span id="Branch-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=branch_view_parent]').hide(); }else{ $j('.btn[id=branch_view_parent]').show(); }

					if(typeof(Branch_update_autofills__RAND__) == 'function') Branch_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
	</script>
	<?php

	$lookups = str_replace('__RAND__', $rnd1, ob_get_contents());
	ob_end_clean();


	// code for template based detail view forms

	// open the detail view template
	if($dvprint){
		$template_file = is_file("./{$TemplateDVP}") ? "./{$TemplateDVP}" : './templates/feescollection_templateDVP.html';
		$templateCode = @file_get_contents($template_file);
	}else{
		$template_file = is_file("./{$TemplateDV}") ? "./{$TemplateDV}" : './templates/feescollection_templateDV.html';
		$templateCode = @file_get_contents($template_file);
	}

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'FeesCollection details', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', ($_REQUEST['Embedded'] ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($arrPerm[1] && !$selected_id){ // allow insert and no record selected?
		if(!$selected_id) $templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1" onclick="return feescollection_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1" onclick="return feescollection_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	}else{
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if($_REQUEST['Embedded']){
		$backAction = 'AppGini.closeParentModal(); return false;';
	}else{
		$backAction = '$j(\'form\').eq(0).attr(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;';
	}

	if($selected_id){
		if(!$_REQUEST['Embedded']) $templateCode = str_replace('<%%DVPRINT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" onclick="$$(\'form\')[0].writeAttribute(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;" title="' . html_attr($Translation['Print Preview']) . '"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($AllowUpdate){
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" onclick="return feescollection_validateData();" title="' . html_attr($Translation['Save Changes']) . '"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		}else{
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		}
		if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3){ // allow delete?
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" onclick="return confirm(\'' . $Translation['are you sure?'] . '\');" title="' . html_attr($Translation['Delete']) . '"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		}else{
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		}
		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	}else{
		$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', ($ShowCancel ? '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>' : ''), $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(($selected_id && !$AllowUpdate) || (!$selected_id && !$AllowInsert)){
		$jsReadOnly .= "\tjQuery('#Student').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#Student_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#Session').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#Session_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#PaidAmount').replaceWith('<div class=\"form-control-static\" id=\"PaidAmount\">' + (jQuery('#PaidAmount').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#Branch').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#Branch_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#Remarks').replaceWith('<div class=\"form-control-static\" id=\"Remarks\">' + (jQuery('#Remarks').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('.select2-container').hide();\n";

		$noUploads = true;
	}elseif(($AllowInsert && !$selected_id) || ($AllowUpdate && $selected_id)){
		$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', true);"; // temporarily disable form change handler
			$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos
	$templateCode = str_replace('<%%COMBO(Student)%%>', $combo_Student->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(Student)%%>', $combo_Student->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(Student)%%>', urlencode($combo_Student->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(Session)%%>', $combo_Session->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(Session)%%>', $combo_Session->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(Session)%%>', urlencode($combo_Session->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(Branch)%%>', $combo_Branch->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(Branch)%%>', $combo_Branch->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(Branch)%%>', urlencode($combo_Branch->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(Date)%%>', ($selected_id && !$arrPerm[3] ? '<div class="form-control-static">' . $combo_Date->GetHTML(true) . '</div>' : $combo_Date->GetHTML()), $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(Date)%%>', $combo_Date->GetHTML(true), $templateCode);

	/* lookup fields array: 'lookup field name' => array('parent table name', 'lookup field caption') */
	$lookup_fields = array(  'Student' => array('students', 'Student'), 'Session' => array('sessions', 'Session'), 'Branch' => array('branch', 'Branch'));
	foreach($lookup_fields as $luf => $ptfc){
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if($pt_perm['view'] || $pt_perm['edit']){
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent hspacer-md" id="' . $ptfc[0] . '_view_parent" title="' . html_attr($Translation['View'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] && !$_REQUEST['Embedded']){
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-success add_new_parent hspacer-md" id="' . $ptfc[0] . '_add_new" title="' . html_attr($Translation['Add New'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-plus-sign"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode = str_replace('<%%UPLOADFILE(id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Student)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Session)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(PaidAmount)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Branch)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Date)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Remarks)%%>', '', $templateCode);

	// process values
	if($selected_id){
		if( $dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', safe_html($urow['id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', html_attr($row['id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode($urow['id']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Student)%%>', safe_html($urow['Student']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Student)%%>', html_attr($row['Student']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Student)%%>', urlencode($urow['Student']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Session)%%>', safe_html($urow['Session']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Session)%%>', html_attr($row['Session']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Session)%%>', urlencode($urow['Session']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(PaidAmount)%%>', safe_html($urow['PaidAmount']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(PaidAmount)%%>', html_attr($row['PaidAmount']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(PaidAmount)%%>', urlencode($urow['PaidAmount']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Branch)%%>', safe_html($urow['Branch']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Branch)%%>', html_attr($row['Branch']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Branch)%%>', urlencode($urow['Branch']), $templateCode);
		$templateCode = str_replace('<%%VALUE(Date)%%>', @date('m/d/Y', @strtotime(html_attr($row['Date']))), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Date)%%>', urlencode(@date('m/d/Y', @strtotime(html_attr($urow['Date'])))), $templateCode);
		if($dvprint || (!$AllowUpdate && !$AllowInsert)){
			$templateCode = str_replace('<%%VALUE(Remarks)%%>', safe_html($urow['Remarks']), $templateCode);
		}else{
			$templateCode = str_replace('<%%VALUE(Remarks)%%>', html_attr($row['Remarks']), $templateCode);
		}
		$templateCode = str_replace('<%%URLVALUE(Remarks)%%>', urlencode($urow['Remarks']), $templateCode);
	}else{
		$templateCode = str_replace('<%%VALUE(id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Student)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Student)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Session)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Session)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(PaidAmount)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(PaidAmount)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Branch)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Branch)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Date)%%>', '<%%creationDate%%>', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Date)%%>', urlencode('<%%creationDate%%>'), $templateCode);
		$templateCode = str_replace('<%%VALUE(Remarks)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Remarks)%%>', urlencode(''), $templateCode);
	}

	// process translations
	foreach($Translation as $symbol=>$trans){
		$templateCode = str_replace("<%%TRANSLATION($symbol)%%>", $trans, $templateCode);
	}

	// clear scrap
	$templateCode = str_replace('<%%', '<!-- ', $templateCode);
	$templateCode = str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if($_REQUEST['dvprint_x'] == ''){
		$templateCode .= "\n\n<script>\$j(function(){\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption){
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$selected_id){
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';

	$templateCode .= "\tStudent_update_autofills$rnd1 = function(){\n";
	$templateCode .= "\t\t\$j.ajax({\n";
	if($dvprint){
		$templateCode .= "\t\t\turl: 'feescollection_autofill.php?rnd1=$rnd1&mfk=Student&id=' + encodeURIComponent('".addslashes($row['Student'])."'),\n";
		$templateCode .= "\t\t\tcontentType: 'application/x-www-form-urlencoded; charset=" . datalist_db_encoding . "', type: 'GET'\n";
	}else{
		$templateCode .= "\t\t\turl: 'feescollection_autofill.php?rnd1=$rnd1&mfk=Student&id=' + encodeURIComponent(AppGini.current_Student{$rnd1}.value),\n";
		$templateCode .= "\t\t\tcontentType: 'application/x-www-form-urlencoded; charset=" . datalist_db_encoding . "', type: 'GET', beforeSend: function(){ \$j('#Student$rnd1').prop('disabled', true); \$j('#StudentLoading').html('<img src=loading.gif align=top>'); }, complete: function(){".(($arrPerm[1] || (($arrPerm[3] == 1 && $ownerMemberID == getLoggedMemberID()) || ($arrPerm[3] == 2 && $ownerGroupID == getLoggedGroupID()) || $arrPerm[3] == 3)) ? "\$j('#Student$rnd1').prop('disabled', false); " : "\$j('#Student$rnd1').prop('disabled', true); ")."\$j('#StudentLoading').html('');}\n";
	}
	$templateCode.="\t\t});\n";
	$templateCode.="\t};\n";
	if(!$dvprint) $templateCode.="\tif(\$j('#Student_caption').length) \$j('#Student_caption').click(function(){ Student_update_autofills$rnd1(); });\n";


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	/* default field values */
	$rdata = $jdata = get_defaults('feescollection');
	if($selected_id){
		$jdata = get_joined_record('feescollection', $selected_id);
		if($jdata === false) $jdata = get_defaults('feescollection');
		$rdata = $row;
	}
	$cache_data = array(
		'rdata' => array_map('nl2br', array_map('addslashes', $rdata)),
		'jdata' => array_map('nl2br', array_map('addslashes', $jdata))
	);
	$templateCode .= loadView('feescollection-ajax-cache', $cache_data);

	// hook: feescollection_dv
	if(function_exists('feescollection_dv')){
		$args=array();
		feescollection_dv(($selected_id ? $selected_id : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}
?>