<?php
// This script and data application were generated by AppGini 5.70
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/schoolmoney.php");
	include("$currDir/schoolmoney_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('schoolmoney');
	if(!$perm[0]){
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "schoolmoney";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = array(   
		"`schoolmoney`.`id`" => "id",
		"IF(    CHAR_LENGTH(`classes1`.`Name`), CONCAT_WS('',   `classes1`.`Name`), '') /* Class */" => "Class",
		"`schoolmoney`.`Particulars`" => "Particulars",
		"`schoolmoney`.`Total`" => "Total"
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(   
		1 => '`schoolmoney`.`id`',
		2 => '`classes1`.`Name`',
		3 => 3,
		4 => '`schoolmoney`.`Total`'
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = array(   
		"`schoolmoney`.`id`" => "id",
		"IF(    CHAR_LENGTH(`classes1`.`Name`), CONCAT_WS('',   `classes1`.`Name`), '') /* Class */" => "Class",
		"`schoolmoney`.`Particulars`" => "Particulars",
		"`schoolmoney`.`Total`" => "Total"
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters = array(   
		"`schoolmoney`.`id`" => "ID",
		"IF(    CHAR_LENGTH(`classes1`.`Name`), CONCAT_WS('',   `classes1`.`Name`), '') /* Class */" => "Class",
		"`schoolmoney`.`Particulars`" => "Particulars",
		"`schoolmoney`.`Total`" => "Total"
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS = array(   
		"`schoolmoney`.`id`" => "id",
		"IF(    CHAR_LENGTH(`classes1`.`Name`), CONCAT_WS('',   `classes1`.`Name`), '') /* Class */" => "Class",
		"`schoolmoney`.`Particulars`" => "Particulars",
		"`schoolmoney`.`Total`" => "Total"
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array(  'Class' => 'Class');

	$x->QueryFrom = "`schoolmoney` LEFT JOIN `classes` as classes1 ON `classes1`.`id`=`schoolmoney`.`Class` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowMassDelete = false;
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 0;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "schoolmoney_view.php";
	$x->RedirectAfterInsert = "schoolmoney_view.php?SelectedID=#ID#";
	$x->TableTitle = "Estructura de Tarifas";
	$x->TableIcon = "resources/table_icons/coins_add.png";
	$x->PrimaryKey = "`schoolmoney`.`id`";

	$x->ColWidth   = array(  150, 150, 150);
	$x->ColCaption = array("Clase", "Observaciones", "Total");
	$x->ColFieldName = array('Class', 'Particulars', 'Total');
	$x->ColNumber  = array(2, 3, 4);

	// template paths below are based on the app main directory
	$x->Template = 'templates/schoolmoney_templateTV.html';
	$x->SelectedTemplate = 'templates/schoolmoney_templateTVS.html';
	$x->TemplateDV = 'templates/schoolmoney_templateDV.html';
	$x->TemplateDVP = 'templates/schoolmoney_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->ShowRecordSlots = 0;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HighlightColor = '#FFF0C2';

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))){ $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])){ // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `schoolmoney`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='schoolmoney' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])){ // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `schoolmoney`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='schoolmoney' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3){ // view all
		// no further action
	}elseif($perm[2]==0){ // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`schoolmoney`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: schoolmoney_init
	$render=TRUE;
	if(function_exists('schoolmoney_init')){
		$args=array();
		$render=schoolmoney_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: schoolmoney_header
	$headerCode='';
	if(function_exists('schoolmoney_header')){
		$args=array();
		$headerCode=schoolmoney_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode){
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: schoolmoney_footer
	$footerCode='';
	if(function_exists('schoolmoney_footer')){
		$args=array();
		$footerCode=schoolmoney_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode){
		include_once("$currDir/footer.php"); 
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>